[package]
name = "rust_learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "hello_world",
    "variable_and_function",
    "number_arithmetic_operation",
    "trait_rs",
    "from_into",
    "vec",
    "more_destructuring",
    "dereferencing_and_the_dot_operator",
    "generics",
    "more_generics",
    "option",
    "more_option",
    "result",
    "more_result"
]